INSERT INTO Users (username, is_admin) 
VALUES ('sdiener', true);

INSERT INTO Translations (translation)
VALUES ('NIV'), ('NASB'), ('ESV'), ('NKJV'), ('NLT');

INSERT INTO Insights (insight_date, insight, category_id)
VALUES ('2022-07-23', `
    (1 Peter 3) 3:11 says we must "turn" from evil and do good. I like the picture of actually turning away from evil, not tyring
    to get both good and evil. (evil---us---good), which way will we turn? Good and evil are in complete opposite directions, so
    we really can't have both or they'll pull us apart. To fully turn from evil, we have to sever all ties to it and not look back.
`, 1);

INSERT INTO ScriptureWriting (book, chapters_in_book, translation_id)
VALUES ('Genesis', 50, 1),
('Exodus', 40, 1),
('Leviticus', 27, 1),
('Numbers', 36, 1),
('Deuteronomy', 34, 1),
('Joshua', 24, 1),
('Judges', 21, 1),
('Ruth', 4, 1),
('1 Samuel', 31, 1),
('2 Samuel', 24, 1),
('1 Kings', 22, 1),
('2 Kings', 25, 1),
('1 Chronicles', 29, 1),
('2 Chronicles', 36, 1),
('Ezra', 10, 1),
('Nehemiah', 13, 1),
('Esther', 10, 1),
('Job', 42, 1),
('Psalms', 150, 1),
('Proverbs', 31, 1),
('Ecclesiastes', 12, 1),
('Song of Songs', 8, 1),
('Isaiah', 66, 1),
('Jeremiah', 52, 1),
('Lamentations', 5, 1),
('Ezekiel', 48, 1),
('Daniel', 12, 1),
('Hosea', 14, 1),
('Joel', 3, 1),
('Amos', 9, 1),
('Obadiah', 1, 1),
('Jonah', 4, 1),
('Micah', 7, 1),
('Nahum', 3, 1),
('Habakkuk', 3, 1),
('Zephaniah', 3, 1),
('Haggai', 2, 1),
('Zechariah', 14, 1),
('Malachi', 4, 1),
('Matthew', 28, 1),
('Mark', 16, 1),
('Luke', 24, 1),
('John', 21, 1),
('Acts', 28, 1),
('Romans', 16, 1),
('1 Corinthians', 16, 1),
('2 Corinthians', 13, 1),
('Galatians', 6, 1),
('Ephesians', 6, 1),
('Philippians', 4, 1),
('Colossians', 4, 1),
('1 Thessalonians', 5, 1),
('2 Thessalonians', 3, 1),
('1 Timothy', 6, 1),
('2 Timothy', 4, 1),
('Titus', 3, 1),
('Philemon', 1, 1),
('Hebrews', 13, 1),
('James', 5, 1),
('1 Peter', 5, 1),
('2 Peter', 3, 1),
('1 John', 5, 1),
('2 John', 1, 1),
('3 John', 1, 1),
('Jude', 1, 1),
('Revelation', 22, 1);